title: "Resilience by Cyan"
description: "Notes on research & projects"
url: "https://kucyans.github.io/KUcyans.github.io-resilience"

remote_theme: LeNPaul/Millennial
plugins:
  - jekyll-remote-theme
  - jekyll-feed
