# Basic site settings
title: "KUcyans â€“ Resilience"
description: "Notes on research & projects"

# Navigation menu
menu:
  - { name: "Home", link: "/" }
  - { name: "About", link: "/about/" }
  - { name: "Projects", link: "/projects/" }

# Social icons (optional)
social:
  - { icon: "github", link: "https://github.com/KUcyans" }

